- name: "Accessories"
  description: "Accessories"
  critical: false
  hidden: false
  selected: false
  expanded: true
  packages:
    - cheese
    - font-manager-git
    - galculator
    - gpick
    - flameshot
    - liferea
    - mediainfo
    - mcomix
    - nitrogen
    - nomacs
    - pdfarranger
    - plank
    - arcolinux-plank-themes-git
    - screenkey-git
    - xfburn
    - vim-plugins
- name: "Fonts"
  description: "Fonts"
  critical: false
  hidden: false
  selected: false
  expanded: true
  packages:
    - terminus-font
    - ttf-bitstream-vera
    - ttf-fira-code
    - ttf-inconsolata
    - ttf-liberation
- name: "Git"
  description: "Git applications"
  critical: false
  hidden: false
  selected: false
  expanded: true
  packages:
    - gitahead-bin
    - gitg
    - gitfiend
    - gitkraken
- name: "Fun"
  description: "Fun script from ArcoLinux"
  critical: false
  hidden: false
  selected: false
  expanded: true
  packages:
    - arcolinux-meta-fun
- name: "Password Manager"
  description: "Password managers"
  critical: false
  hidden: false
  selected: false
  expanded: true
  packages:
    - bitwarden-bin
    - enpass-bin
    - keepassxc
    - lastpass
- name: "Privacy"
  description: "Applications that ensure your privacy"
  critical: false
  hidden: false
  selected: false
  expanded: true
  packages:
    - tor-browser
    - tor
    - privoxy
- name: "Usb"
  description: "Usb writing applications"
  critical: false
  hidden: false
  selected: false
  expanded: true
  packages:
    - etcher-bin
    - imagewriter
    - woeusb
- name: "Virtualbox for Linux kernel"
  description: "Installs virtualbox for linux kernel"
  critical: false
  hidden: false
  selected: false
  expanded: false
  packages:
    - virtualbox
    - virtualbox-host-dkms
    - linux-headers
- name: "Virtualbox for Linux-lts kernel"
  description: "Installs virtualbox for linux-lts kernel"
  critical: false
  hidden: false
  selected: false
  expanded: false
  packages:
    - virtualbox
    - virtualbox-host-dkms
    - linux-lts-headers
    - linux-lts
